/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author USER
 */
public class RoundedBorderExample extends javax.swing.JPanel {
 private int cornerRadius = 30;
    /**
     * Creates new form RoundedBorderExample
     */
    public RoundedBorderExample() {
        initComponents();
        
    }
      
    protected void paintComponent(Graphics g) {
        // Gọi phương thức paintComponent của lớp cha để vẽ các thành phần khác
        super.paintComponent(g);
        
        // Chuyển đổi Graphics sang Graphics2D để vẽ bo tròn
        Graphics2D g2d = (Graphics2D) g;
        
        // Kích hoạt hiệu ứng anti-aliasing để vẽ mượt mà hơn
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        // Vẽ nền với bo tròn
        g2d.setColor(new Color(119, 221, 119));  // Màu nền của panel, có thể thay đổi
        g2d.fillRoundRect(0, 0, getWidth(), getHeight(), cornerRadius, cornerRadius);  // Vẽ hình chữ nhật bo tròn
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
